name = "claws"
type = "javascript"

account_id = "<ACCOUNT_ID>"

compatibility_date = "2021-09-23"

[build]
command = "yarn install && yarn run build:production"

[build.upload]
dir = "dist"
format = "modules"
main = "index.mjs"

[env.production]
route = "<DOMAIN>/*"
zone_id = "<ZONE_ID>"
