name = "claws"
type = "javascript"

account_id = "<ACCOUNT_ID>"
workers_dev = true

[build]
command = "npm install && npm run build:production"

[build.upload]
format = "modules"
main = "index.mjs"

[env.production]
zone_id = "<ZONE_ID>"
route = "<DOMAIN>/*"
