name = "claws"
compatibility_date = "2022-05-18"
main = "dist/index.mjs"

workers_dev = false
account_id = "<ACCOUNT_ID>"
route = { pattern = "claws.<DOMAIN>/*", zone_name = "<DOMAIN>" }

[build]
command = "yarn install --immutable && yarn run build"
