name = "claws"
type = "javascript"

account_id = "<ACCOUNT_ID>"

[build]
command = "yarn install && yarn run build:production"

[build.upload]
format = "service-worker"

[env.production]
route = "<DOMAIN>/*"
zone_id = "<ZONE_ID>"
